### ISSUE TITLE
Wireless Crafting Terminal issues

### ISSUE THREAD

**Issue by Lingaaah** [al132mc/antimatter-chemistry#141] opened 2019-07-14 09:11 UTC
So when attempting to make the wireless crafting terminal in 1.2.14 the game crashes when trying to craft it. Tried in vanilla crafting table and recipe didnt show anything to make, thank you!

**Comment by Next-victim** [comment] 2019-07-14 15:22
Duplicate of issue #113 ( https://github.com/al132mc/antimatter-chemistry/issues/113 )

**Closed** 2019-07-14 15:25 UTC
