### ISSUE TITLE
Rnadom crash, provided logs

### ISSUE THREAD

**Issue by Cavann** [al132mc/antimatter-chemistry#230] opened 2020-03-04 20:10 UTC
[latest.log](https://github.com/al132mc/antimatter-chemistry/files/4289476/latest.log)

**Comment by ghost** [comment] 2020-03-04 20:47
Known issue (beyond my control, and unfixable because extra utilities is no longer maintained) Duplicate of #161 . See that issue for advice on how to avoid this crash

**Closed as completed by ghost** 2020-03-04 20:47 UTC
