### ISSUE TITLE
Ticking Block Entity Crash 

### ISSUE THREAD

**Issue by madder47** [al132mc/antimatter-chemistry#223] opened 2020-02-11 23:18 UTC
[crash-2020-02-10_21.24.06-server.txt](https://github.com/al132mc/antimatter-chemistry/files/4189100/crash-2020-02-10_21.24.06-server.txt)

First time reporting an issue, hopefully this is the correct way.

**Comment by ranid007** [comment] 2020-03-23 20:24
same issue. Caughted NullPointer by EU (Errored by Compressed Cobblestone). Its repeatable [https://paste.ee/p/GyEqc ](url) [https://bit.ly/Crash-log](url)

**Comment by MasterEnderman** [comment] 2022-05-04 13:31
Duplicate of #161

**Closed as completed by MasterEnderman** 2022-05-04 13:31 UTC
Labels: Crash Bug, duplicate, Mod Bug
