### ISSUE TITLE
[CRASH] creating compressed cobblestone crashes the game

### ISSUE THREAD

**Issue by KingofJupiter** [al132mc/antimatter-chemistry#235] opened 2020-03-31 01:07 UTC
So the game crashes every now and then when I try to create compressed cobblestone. It will work for a little bit but then the game eventually crashes.

Error: java.lang.NullPointerException: at index 0

**Comment by ghost** [comment] 2020-03-31 12:08
Duplicate of https://github.com/al132mc/antimatter-chemistry/issues/161 . For compressed cobble use a vanilla crafting table or your AE2/RS system, for some reason it crashes with the tinkers workbench

**Closed as completed by ghost** 2020-03-31 12:08 UTC
