### ISSUE TITLE
Crashes dubbel compressed Cobblestone 

### ISSUE THREAD

**Issue by NLinCH** [al132mc/antimatter-chemistry#204] opened 2019-10-20 10:44 UTC
my game crashed twice when using double compressed cobblestone
once when placing it against the side of a compacting drawer
once when taking it the last pieces out of a tinkers table after crafting triple compressed cobblestone.

I feel as if the item might not be fully stable.
please commend if someone finds similar instability's of any compressed Cobblestone.

Thanks should anyone find the time and motivation to check the problems.
here are the Crash-report files

[crash-2019-10-20_10.40.21-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3747727/crash-2019-10-20_10.40.21-client.txt)
[crash-2019-10-20_12.35.53-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3747728/crash-2019-10-20_12.35.53-client.txt)

**Comment by ghost** [comment] 2019-10-20 14:09
Duplicate of https://github.com/al132mc/antimatter-chemistry/issues/161

**Closed as completed** 2019-10-27 15:41 UTC
