### ISSUE TITLE
Cobalt Large Plate doesn't form correctly from Tinker's Smeltery

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#38] opened 2019-05-25 22:35 UTC
From Discord user: @Alfa19701

Noted in the video at https://youtu.be/7Zn21Q070y4 between 11min30 to 12min15

When pouring Cobalt from the Tinker's smeltery, Large Plate doesn't form correctly. It seems to take Cobalt and not give a percentage for the progress on the plate. Picture from Alfa19701's youtube video, where the percent load doesn't appear, below.

![Capture-3](https://user-images.githubusercontent.com/51034324/58375177-4598d800-7f1b-11e9-91c1-bc7585030723.PNG)

**Comment by Next-victim** [comment] 2019-05-26 09:24
Heads up, may have been something with OP's pack or setup. 

Just made the Cobalt plate myself and had no issues aside from it not showing how full the cast was (it showed cooling correctly though). Image of it cooling below.

Might want to give them a DM in discord (username in the main ticket) to ask about pack version and if their cobalt might be going somewhere other than intended?

![2019-05-26_05 17 46](https://user-images.githubusercontent.com/51034324/58379755-1499c100-7f76-11e9-979b-5c212861982f.png)

**Comment by al132mc** [comment] 2019-05-26 15:16
Indeed, this is pretty odd. I've never heard of anyone else having this issue.

**Comment by kevsgrove** [comment] 2019-06-06 02:12
Pretty certain the progress bar didn't show because of the WAILA (or whatever the updated version is called) settings: he wasn't holding shift.

He also only poured 4 ingots in initially, then added 8 more, and 4 ingots were left in the smeltery. This behaves correctly (the plate takes 8 ingots), though I'm not sure why he said it vanished. He doesn't check the chest/hopper. I'd wager that the hopper pulled it out as intended.

**Comment by al132mc** [comment] 2019-06-06 02:13
This has happened to literally nobody else to the best of my knowledge, and this is plausible explaination, so i'll close this. If anyone else experiences this issue they can comment here or create a new issue.

**Closed by al132mc** 2019-06-06 02:13 UTC
Labels: question
