### ISSUE TITLE
[Bug] Freeze with Liquid RFTDim using Nuclearcraft Molten Thorium

### ISSUE THREAD

**Issue by lrwerewolf** [al132mc/antimatter-chemistry#214] opened 2019-12-04 01:43 UTC
Wanting a better source of thorium for my reactors, I attempted to create a dimension filled with molten thorium (liquid terrain, none/normal for most else, time noon).  When I ported into that dimension, the game lags to the point of nearly nonresponsive, with the log filling up with errors about being unable to keep up, with delays between ticks hitting  as high as 120 seconds.

Looking at the 'latest.log', when I crash it out, it looks like the error is in the BufferBuilder.  I noticed that Molten Thorium, when placed in world, seems to have a placeholder texture or an error texture (traditional magenta/black, but with text on it).  Trying to diagnose this on my own, I found some sites suggesting that it might be JourneyMap, but disabling this mod did not lead to resolution (though the lag times did drop a good bit, but still 60sec and above at times).  Because of this drop, I suspect the texture may have something to do with it.

I tried allowing the game to run, hoping perhaps it would self-fix given enough time to figure out whatever it's doing, but it ends up crashing out with an out-of-memory 'at net.minecraft.client.renderer.BufferBuilder.func_181672_a(BufferBuilder.java:135)'

Unfortunately, the lag is so severe I'm unable to get LagGoggles to run.

If this needs to be redirected to a mod-specific issue tracker please let me know or feel free to open the issue on my behalf.

**Comment by lrwerewolf** [comment] 2019-12-04 02:13
Quick further note: using a world editor to change my position to my base back in Overworld, I'm able to play again with no ill effects so long as I don't return to the dimension.  Occurs to me [Suggestion] Enable thorium ore and uranium ore dimlets?

**Comment by ghost** [comment] 2019-12-12 17:02
Hm, i'm not able to get custom dimlets to work, anyone please reply if you know what the issue is... i'm using the automatically registered tinkers ore dimlets as my reference

```
  {
    "filter": {
      "mod": "nuclearcraft",
      "name": "ore",
      "type": "material",
      "property": {
        "type": "thorium"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "nuclearcraft",
      "name": "ore",
      "type": "material",
      "property": {
        "type": "uranium"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  }
```

**Comment by lrwerewolf** [comment] 2019-12-18 10:29
So regenerate the default config/dimlet.json -- I see you removed the 'everything below...' lined and I find this doesn't work so great.

In my experimentation, I added the following above that line I added the thorium block and uranium block, which I see as being worth much more as per-block it yields more ingots than the per-block yield of the ore, 2.5 ingots max.  I also added the other metals as blocks.  I also made none of them worldgen to make the player have to acquire at least a stockpile of the desired block before being able to access a dimension (yielding essentially unlimited amounts).  Change the values as you wish:
```
  {
    "filter": {
      "mod": "nuclearcraft",
      "name": "ore",
      "meta": [
        3,
        4,
        5,
        6,
        7
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "nuclearcraft",
      "name": "ingot_block",
      "meta": [
        3,
        4
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 320000,
      "maintain": 20000,
      "ticks": 3000,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "nuclearcraft",
      "name": "ingot_block",
      "meta": [
        5,
        6,
        7,
        8
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 10000,
      "maintain": 2000,
      "ticks": 1000,
      "worldgen": false,
      "dimlet": true
    }
  },

```

**Comment by idiosync** [comment] 2020-05-18 07:36
@lrwerewolf Thank you for the solution. You helped out on my world when dealing with the liquid uranium. I added @al132mc 's json to above the regened dimlet.json file and it worked for me.

**Comment by MasterEnderman** [comment] 2022-05-06 08:42
Fixed with the next update -> added nuclearcraft fluids to RFTDim blacklist.

**Comment by MasterEnderman** [comment] 2022-05-06 16:18
Update: all nuclearcraft fluids should work in RFTools DImensions with the changes made in #272 
that means they won't be blacklisted with the next update.

**Closed as completed** 2022-05-10 13:52 UTC
Labels: Fixed in dev
